bridges = []

[[instances]]
name = "Learning Pathways"
id = "__learning-pathways"
dna_hash = "QmW3vYa8fu1zDNCaZNCEKYzd77CNVkH4f3a3a2erFThuNi"
uri = "https://github.com/holochain/basic-chat/releases/download/v0.1.2/basic-chat.dna.json"

[[UIs]]
name = "Learning Pathways"
id = "leap-ui"
ui_bundle_hash = "Qm34abcde"
uri = "https://github.com/holochain/basic-chat/releases/download/v0.1.2/ui.zip"

[[UIs.instance_references]]
ui_handle = "learning-pathways"
instance_id = "__learning-pathways-public"
